package gui

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/jesseduffield/lazydocker/pkg/commands"
)

const generatedConfigWarning = "# Generated by lazydocker for inspection only.\n# Edits to this temporary file do not change Docker or Compose source files.\n\n"

func generatedConfigFilePattern(kind, name string) string {
	name = strings.Map(func(character rune) rune {
		if unicode.IsLetter(character) || unicode.IsDigit(character) || strings.ContainsRune("-_.", character) {
			return character
		}
		return '-'
	}, name)
	name = strings.Trim(name, "-.")
	if name == "" {
		name = "config"
	}

	return fmt.Sprintf("lazydocker-%s-%s-*.yaml", kind, name)
}

func generatedConfigContent(content string) string {
	return generatedConfigWarning + content
}

func (gui *Gui) composeConfigAvailabilityError(projectName string) string {
	if !gui.DockerCommand.InDockerComposeProject {
		return gui.Tr.ComposeConfigUnavailable
	}
	if projectName != gui.DockerCommand.LocalProjectName {
		return gui.Tr.CannotViewNonLocalConfig
	}
	return ""
}

func withGeneratedConfigFile(osCommand *commands.OSCommand, kind, name, content string, edit func(string) error) (returnErr error) {
	filename, err := osCommand.CreateTempFile(
		generatedConfigFilePattern(kind, name),
		generatedConfigContent(content),
	)
	if err != nil {
		return err
	}
	defer func() {
		if err := osCommand.Remove(filename); err != nil && returnErr == nil {
			returnErr = err
		}
	}()

	return edit(filename)
}

func (gui *Gui) editGeneratedConfig(kind, name, content string) error {
	err := withGeneratedConfigFile(gui.OSCommand, kind, name, content, gui.editFile)
	if err != nil {
		return gui.createErrorPanel(err.Error())
	}
	return nil
}
